database:
  type: mysql
  IP: 47.117.136.250
  port: 3306
  name: go
  username: root
  password: 123456
  charset: utf8mb4
server:
  port: 8081
logger:
  level: debug
  filename: run.log
  maxsize: 200
  max_age: 7
  max_backups: 10